framework:
    messenger:
        default_bus: command.bus
#        failure_transport: failed
        buses:
            command.bus:
                middleware:
                    - validation
                    - App\Messenger\Middleware\LockMiddleware
                    - App\Messenger\Middleware\UnwrapHandlerExceptionMiddleware

            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
                    - App\Messenger\Middleware\LockMiddleware
                    - App\Messenger\Middleware\UnwrapHandlerExceptionMiddleware

        transports:
             sync: 'sync://'

        routing:
            # 'App\Message\YourMessage': async

#when@test:
#    framework:
#        messenger:
#            transports:
#                sync: 'test://?catch_exceptions=false'
#                workqueue: 'test://?catch_exceptions=false'
